### ISSUE TITLE
USER STORY: Source and integrate images

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/may-hackathon-2024#9]
### If applicable, add a related Epic.

EPIC: Sound and Visual Assets

### User Story

As a team, we need to source Star Wars images so that we can use them in the mini-games and storyline.

### Acceptance Criteria

- Images are sourced
- Images are relevant and high-quality
- Images are integrated into the game

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Reviewed the user story for clarity and completeness.
- [x] Updated the issue with any relevant notes or feedback (to date).

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [x] Find images
- [x] Ensure images are high-quality
- [x] Integrate images into the game

**Comment by creepersguitar** [comment]
Are we doing planets? ships? people? places? for the images?
I'll get a collection of all above to help :)

**Comment by stephendawsondev** [comment]
> Are we doing planets? ships? people? places? for the images? I'll get a collection of all above to help :)
I think you know more or less after the meeting! So mostly linked to the story! Make sure to save the references to them for attribution later!

**Comment by stephendawsondev** [comment]
@creepersguitar Would you be able to create a PR and add the images to the repo for visibility? I recommend doing a `git pull upstream main` first so that you have the most up-to-date versions, since @hannahro15 has already added some wireframes.

**Comment by stephendawsondev** [comment]
Closing as this looks to be complete!
